[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { version = "0.18", features = ["persistence"] }
# egui_extras = { version = "0.18", features = ["serde"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
confy = "0.4"
ureq = { version = "2.4", features = ["json"] }
reqwest = { version = "0.11", features = ["json"] }

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
gloo-timers = "0.2.4"
reqwasm = "0.5"
wasm-bindgen-futures = "0.4.30"

js-sys = "0.3"
wasm-bindgen = "0.2"


[profile.release]
strip = true
lto = true
opt-level = 2
