[package]
name = "client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18"
egui_extras = "0.18"
anyhow = "1.0"
env_logger = "0.9"
log = "0.4"
serde = "1.0"
